myproject/urls.py
from __future__ import unicode_literals

import mezzanine.blog.views
import mezzanine.pages.views
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.views.i18n import set_language

from mezzanine.core.views import direct_to_template
from mezzanine.conf import settings

from blogs.views import blog_edit, blog_list, blog_detail, blog_new, blog_post_new, blog_post_edit, blog_post_detail, \
    author_list

admin.autodiscover()

_slash = "/" if settings.APPEND_SLASH else ""
# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

urlpatterns = i18n_patterns(
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
    url("^admin/", include(admin.site.urls)),
)

if settings.USE_MODELTRANSLATION:
    urlpatterns += [
        url('^i18n/$', set_language, name='set_language'),
    ]

urlpatterns += [
    # url("^posts/(?P<slug>.*)/$", blog_post_detail, name="blog_post_detail"),

    url("^blogs/(?P<slug>.*)/edit/$", blog_edit, name="blog_edit"),
    url("^blogs/$", blog_list, name="blog_list"),
    url('^blogs/new/$', blog_new, name='blog_new'),
    url("^blogs/(?P<slug>.*)/$", blog_detail, name="blog_detail"),

    url("^posts/new/$", blog_post_new, name="blog_post_new"),
    url("^posts/(?P<slug>.*)/edit/$", blog_post_edit, name="blog_post_edit"),

    url("^users/$", author_list, name="author_list"),

    # We don't want to presume how your homepage works, so here are a
    # few patterns you can use to set it up.

    # HOMEPAGE AS STATIC TEMPLATE
    # ---------------------------
    # This pattern simply loads the index.html template. It isn't
    # commented out like the others, so it's the default. You only need
    # one homepage pattern, so if you use a different one, comment this
    # one out.

    # url("^$", direct_to_template, {"template": "index.html"}, name="home"),

    # HOMEPAGE AS AN EDITABLE PAGE IN THE PAGE TREE
    # ---------------------------------------------
    # This pattern gives us a normal ``Page`` object, so that your
    # homepage can be managed via the page tree in the admin. If you
    # use this pattern, you'll need to create a page in the page tree,
    # and specify its URL (in the Meta Data section) as "/", which
    # is the value used below in the ``{"slug": "/"}`` part.
    # Also note that the normal rule of adding a custom
    # template per page with the template name using the page's slug
    # doesn't apply here, since we can't have a template called
    # "/.html" - so for this case, the template "pages/index.html"
    # should be used if you want to customize the homepage's template.
    # NOTE: Don't forget to import the view function too!

    # url("^$", mezzanine.pages.views.page, {"slug": "/"}, name="home"),

    # HOMEPAGE FOR A BLOG-ONLY SITE
    # -----------------------------
    # This pattern points the homepage to the blog post listing page,
    # and is useful for sites that are primarily blogs. If you use this
    # pattern, you'll also need to set BLOG_SLUG = "" in your
    # ``settings.py`` module, and delete the blog page object from the
    # page tree in the admin if it was installed.
    # NOTE: Don't forget to import the view function too!

    url("^$", mezzanine.blog.views.blog_post_list, name="home"),

    # MEZZANINE'S URLS
    # ----------------
    # ADD YOUR OWN URLPATTERNS *ABOVE* THE LINE BELOW.
    # ``mezzanine.urls`` INCLUDES A *CATCH ALL* PATTERN
    # FOR PAGES, SO URLPATTERNS ADDED BELOW ``mezzanine.urls``
    # WILL NEVER BE MATCHED!

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    url("^", include("mezzanine.urls")),

    # MOUNTING MEZZANINE UNDER A PREFIX
    # ---------------------------------
    # You can also mount all of Mezzanine's urlpatterns under a
    # URL prefix if desired. When doing this, you need to define the
    # ``SITE_PREFIX`` setting, which will contain the prefix. Eg:
    # SITE_PREFIX = "my/site/prefix"
    # For convenience, and to avoid repeating the prefix, use the
    # commented out pattern below (commenting out the one above of course)
    # which will make use of the ``SITE_PREFIX`` setting. Make sure to
    # add the import ``from django.conf import settings`` to the top
    # of this file as well.
    # Note that for any of the various homepage patterns above, you'll
    # need to use the ``SITE_PREFIX`` setting as well.

    # ("^%s/" % settings.SITE_PREFIX, include("mezzanine.urls"))

]

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

blogs/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext
from mezzanine.blog.models import BlogPost
from mezzanine.core.fields import RichTextField
from mezzanine.core.models import Slugged
from mezzanine.utils.models import base_concrete_model
from mezzanine.utils.urls import unique_slug, slugify
from django.utils.translation import ugettext, ugettext_lazy as _
from myproject.settings import ACCOUNTS_PROFILE_MODEL


class MyBlog(models.Model):
    name = models.CharField(max_length=200)
    description =models.TextField(blank=True)
    author = models.ManyToManyField(ACCOUNTS_PROFILE_MODEL)
    publish_date = models.DateField(auto_now=True, blank=True)
    avatar = models.ImageField(upload_to='uploads/', default='uploads\gallery\Berlin, Germany.jpg', blank=True)
    slug = models.CharField(max_length=2000, blank=True, null=True,
                            help_text="Leave blank to have the URL auto-generated from "
                                        "the title.")

    def get_absolute_url(self):

        url_name = "blog_detail"
        kwargs = {"slug": self.slug}
        return reverse(url_name, kwargs=kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'
        permissions = (
            ('view_myblog', 'View myblog'),
        )




    def save(self, *args, **kwargs):
        """
        If no slug is provided, generates one before saving.
        """
        if not self.slug:
            self.slug = self.generate_unique_slug()
        super(MyBlog, self).save(*args, **kwargs)

    def generate_unique_slug(self):
        """
        Create a unique slug by passing the result of get_slug() to
        utils.urls.unique_slug, which appends an index if necessary.
        """
        # For custom content types, use the ``Page`` instance for
        # slug lookup.
        concrete_model = base_concrete_model(Slugged, self)
        slug_qs = concrete_model.objects.exclude(id=self.id)
        return unique_slug(slug_qs, "slug", self.get_slug())

    def get_slug(self):
        """
        Allows subclasses to implement their own slug creation logic.
        """
        attr = "name"
        # Get self.title_xx where xx is the default language, if any.
        # Get self.title otherwise.
        return slugify(getattr(self, attr, None) or self.name)

    def admin_link(self):
        return "<a href='%s'>%s</a>" % (self.get_absolute_url(),
                                        ugettext("View on site"))

    admin_link.allow_tags = True
    admin_link.short_description = ""


class BlogPostNew(BlogPost):
    blog = models.ForeignKey(MyBlog, blank=True)


    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

templates/pages/author_list.html
{% extends "base.html" %}
{% load i18n mezzanine_tags blog_tags keyword_tags disqus_tags %}

{% block meta_title %}{% if page %}{{ page.meta_title }}{% else %}{% trans "Blog" %}{% endif %}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for page as keywords %}
{% for keyword in keywords %}
    {% if not forloop.first %}, {% endif %}
    {{ keyword }}
{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ page.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% if page %}
{% editable page.title %}{{ page.title }}{% endeditable %}
{% else %}
{% trans "Blog" %}
{% endif %}
{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
{% if tag or category or year or month or author %}
<li>{% spaceless %}
{% if tag %}
    {% trans "Tag:" %} {{ tag }}
{% else %}{% if category %}
    {% trans "Category:" %} {{ category }}
{% else %}{% if year or month %}
    {% if month %}{{ month }}, {% endif %}{{ year }}
{% else %}{% if author %}
    {% trans "Author:" %} {{ author.get_full_name|default:author.username }}
{% endif %}{% endif %}{% endif %}{% endif %}
{% endspaceless %}
</li>
{% endif %}
{% endblock %}

{% block main %}


{% if tag or category or year or month or author %}
    {% block blog_post_list_filterinfo %}
    <p>
    {% if tag %}
        {% trans "Viewing posts tagged" %} {{ tag }}
    {% else %}{% if category %}
        {% trans "Viewing posts for the category" %} {{ category }}
    {% else %}{% if year or month %}
        {% trans "Viewing posts from" %} {% if month %}{{ month }}, {% endif %}
        {{ year }}
    {% else %}{% if author %}
        {% trans "Viewing posts by" %}
        {{ author.get_full_name|default:author.username }}
    {% endif %}{% endif %}{% endif %}{% endif %}
    {% endblock %}
    </p>
{% else %}
    {% if page %}
    {% block blog_post_list_pagecontent %}
    {% if page.get_content_model.content %}
        {% editable page.get_content_model.content %}
        {{ page.get_content_model.content|richtext_filters|safe }}
        {% endeditable %}
    {% endif %}
    {% endblock %}
    {% endif %}
{% endif %}

{% for blog_post in blog_posts %}
<div class="blog-list-detail">
  <table border="0" width="100%" style="margin-bottom: 0px;" >
   <tr>
    <td width=150px;" rowspan="2" >
    <a href="{% url "profile" blog_post.user.username %}"><img style="width: 200px" class="mycss_avatar" src="{{ MEDIA_URL }}{% thumbnail blog_post.avatar 150 150 %}"></a>
    </td>
    <td  style="padding-left: 10px;" >
        <h3 style="margin-top: 0px;" ><a href="{% url "profile" blog_post.user.username %}">{{ blog_post.user.get_full_name }}</a></h3>{{ blog_post.bio }}</td>
   </tr>
   <tr>
    <td style="padding-left: 10px;"><b>Публикатеся в журналах (всего {{ blog_post.myblog_set.all.count }}):</b>
    {% for blog in blog_post.myblog_set.all|slice:":10" %}
     <a href="{{ blog.get_absolute_url }}">{{ blog }}</a>
    {% endfor %}</td>
  </tr>
 </table>
</div>
{% endfor %}

{% pagination_for blog_posts %}
{% endblock %}

{% block right_panel %}
{% include "blog/includes/filter_panel.html" %}
{% endblock %}

templates/pages/blog_detail.html
{% extends "blog/blog_post_list.html" %}
{% load mezzanine_tags comment_tags keyword_tags rating_tags i18n disqus_tags accounts_tags %}

{% block meta_title %}{{ blog_post.meta_title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{#{% keywords_for blog_post as tags %}#}
{% for tag in tags %}{% if not forloop.first %}, {% endif %}{{ tag }}{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ blog_post.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% endblock %}

{% block breadcrumb_menu %}
{{ block.super }}
<li class="active">{{ blog_post.name }}</li>
{% endblock %}



{% block main %}

{#{% block blog_post_detail_postedby %}#}
{#{% block blog_post.publish_date %}#}
{#<h6 class="post-meta">#}
{#    {% trans "Posted by" %}:#}
{#    {% with blog_post.user as author %}#}
{#    <a href="{% url "blog_post_list_author" author %}">{{ author.get_full_name|default:author }}</a>#}
{#    {% endwith %}#}
{#    {% blocktrans with sometime=blog_post.publish_date|timesince %}{{ sometime }} ago{% endblocktrans %}#}
{#</h6>#}
{#{% endblock %}#}
{#{% endblock %}#}
{#{% block blog_post_detail_commentlink %}#}
{#<p>#}
{#    {% if blog_post.allow_comments %}#}
{#        {% if settings.COMMENTS_DISQUS_SHORTNAME %}#}
{#            (<a href="{{ blog_post.get_absolute_url }}#disqus_thread"#}
{#                data-disqus-identifier="{% disqus_id_for blog_post %}">{% spaceless %}#}
{#                {% trans "Comments" %}#}
{#            {% endspaceless %}</a>)#}
{#        {% else %}(<a href="#comments">{% spaceless %}#}
{#            {% blocktrans count comments_count=blog_post.comments_count %}{{ comments_count }} comment{% plural %}{{ comments_count }} comments{% endblocktrans %}#}
{#            {% endspaceless %}</a>)#}
{#        {% endif %}#}
{#    {% endif %}#}
{#</p>#}
{#{% endblock %}#}

{% block blog_post_detail_featured_image %}
{#{% if settings.BLOG_USE_FEATURED_IMAGE and blog_post.featured_image %}#}
{#<p><img class="img-responsive" src="{{ MEDIA_URL }}{% thumbnail blog_post.featured_image 600 0 %}"></p>#}
{#<p><img class="img-responsive" src="{{ MEDIA_URL }}{% thumbnail 'uploads\gallery\Amsterdam, Holland.jpg' 150 200 left=.0 top=.0 %}"></p>#}
{#{% endif %}#}
{% endblock %}

{#{% if settings.COMMENTS_DISQUS_SHORTNAME %}#}
{#{% include "generic/includes/disqus_counts.html" %}#}
{#{% endif %}#}



{% block blog_post_detail_keywords %}
{#{% keywords_for blog_post as tags %}#}
{% if tags %}
{% spaceless %}
<ul class="list-inline tags">
    <li>{% trans "Tags" %}:</li>
    {% for tag in tags %}
    <li><a href="{% url "blog_post_list_tag" tag.slug %}">{{ tag }}</a>{% if not forloop.last %}, {% endif %}</li>
    {% endfor %}
</ul>
{% endspaceless %}
{% endif %}
{% endblock %}

{% block blog_post_detail_rating %}
<div class="panel panel-default rating">
    <div class="panel-body">
 <h2>{{ blog_post.name }}</h2>
        <hr>
{{ blog_post.description|richtext_filters|safe }}
{#        <hr>#}
{#        {% blocktrans with sometime=blog_post.publish_date|timesince %}{{ sometime }} ago{% endblocktrans %}#}
    </div>
</div>
{% endblock %}

{% block blog_post_detail_sharebuttons %}
{#{% set_short_url_for blog_post %}#}
{#<a class="btn btn-default" href="{% url 'blog_edit' slug=blog_post.slug %}"><span class="glyphicon glyphicon-pencil"></span></a>#}
{#<a class="btn btn-sm share-twitter" target="_blank" href="https://twitter.com/intent/tweet?url={{ blog_post.short_url|urlencode }}&amp;text={{ blog_post.title|urlencode }}">{% trans "Share on Twitter" %}</a>#}
{#<a class="btn btn-sm share-facebook" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">{% trans "Share on Facebook" %}</a>#}

{% endblock %}


{#Вывод записей#}


{% if tag or category or year or month or author %}
    {% block blog_post_list_filterinfo %}
    <p>
    {% if tag %}
        {% trans "Viewing posts tagged" %} {{ tag }}
    {% else %}{% if category %}
        {% trans "Viewing posts for the category" %} {{ category }}
    {% else %}{% if year or month %}
        {% trans "Viewing posts from" %} {% if month %}{{ month }}, {% endif %}
        {{ year }}
    {% else %}{% if author %}
        {% trans "Viewing posts by" %}
        {{ author.get_full_name|default:author.username }}
    {% endif %}{% endif %}{% endif %}{% endif %}
    {% endblock %}
    </p>
{% else %}
    {% if page %}
    {% block blog_post_list_pagecontent %}
    {% if page.get_content_model.content %}
        {% editable page.get_content_model.content %}
        {{ page.get_content_model.content|richtext_filters|safe }}
        {% endeditable %}
    {% endif %}
    {% endblock %}
    {% endif %}
{% endif %}

{% for blog_post in blog_posts %}
<h2>
    <a href="{{ blog_post.get_absolute_url }}">{{ blog_post.title }}</a>
</h2>
{% block blog_post_list_post_metainfo %}
{% editable blog_post.publish_date %}
<h6 class="post-meta">
    {% trans "Posted by" %}:
    {% with blog_post.user as author %}
    <a href="{% url "blog_post_list_author" author %}">{{ author.get_full_name|default:author.username }}</a>
    {% endwith %}
    {% with blog_post.categories.all as categories %}
    {% if categories %}
    {% trans "in" %}
    {% for category in categories %}
    <a href="{% url "blog_post_list_category" category.slug %}">{{ category }}</a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% blocktrans with sometime=blog_post.publish_date|timesince %}{{ sometime }} ago{% endblocktrans %}
</h6>
{% endeditable %}
{% endblock %}

{% if settings.BLOG_USE_FEATURED_IMAGE and blog_post.featured_image %}
{% block blog_post_list_post_featured_image %}
<a href="{{ blog_post.get_absolute_url }}">
    <img class="img-thumbnail pull-left" src="{{ MEDIA_URL }}{% thumbnail blog_post.featured_image 90 90 %}">
</a>
{% endblock %}
{% endif %}

{% block blog_post_list_post_content %}
{% editable blog_post.content %}
{{ blog_post.description_from_content|safe }}
{% endeditable %}
{% endblock %}

{% block blog_post_list_post_links %}
<div class="blog-list-detail">
    {% keywords_for blog_post as tags %}
    {% if tags %}
    <ul class="list-inline tags">
    {% trans "Tags" %}:
    {% spaceless %}
    {% for tag in tags %}
    <li><a href="{% url "blog_post_list_tag" tag.slug %}" class="tag">{{ tag }}</a>{% if not forloop.last %}, {% endif %}</li>
    {% endfor %}
    {% endspaceless %}
    </ul>
    {% endif %}
    <p>
    <a href="{{ blog_post.get_absolute_url }}">{% trans "read more" %}</a>
    {% if blog_post.allow_comments %}
    /
    {% if settings.COMMENTS_DISQUS_SHORTNAME %}
    <a href="{{ blog_post.get_absolute_url }}#disqus_thread"
        data-disqus-identifier="{% disqus_id_for blog_post %}">
        {% trans "Comments" %}
    </a>
    {% else %}
    <a href="{{ blog_post.get_absolute_url }}#comments">
        {% blocktrans count comments_count=blog_post.comments_count %}{{ comments_count }} comment{% plural %}{{ comments_count }} comments{% endblocktrans %}
    </a>
    {% endif %}
    {% endif %}
    </p>
</div>
{% endblock %}
{% endfor %}

{% pagination_for blog_posts %}

{#Конец вывод записей#}


{% endblock %}

{% block right_panel %}
{#    <p><img class="img-responsive" src="{{ MEDIA_URL }}{% thumbnail 'uploads\gallery\Amsterdam, Holland.jpg' 250 300 left=.0 top=.0 %}"></p>#}
        <img class="img-thumbnail  mycss_avatar" src="{{ MEDIA_URL }}{% thumbnail blog_post.avatar 250 300 %} ">

   <p><a class="btn btn-default" style="width: 100%" href="{% url 'blog_edit' slug=blog_post.slug %}">Редактировать блог</a></p>
    <p> Авторы:{{ blog_post.author.all.count }} человек</p>
    {% for author in blog_post.author.all %}
     <a href="{% url "profile" author.user.username %}">{{ author.user.get_full_name }}</a>

    {% endfor %}

    {% endblock %}

templates/pages/blog_edit.html
{% extends "pages/page.html" %}

{% load mezzanine_tags i18n %}

{% block extra_head %}
    {{ block.super }}
    {{ form.media }}
{% endblock %}

{% block main %}
{{ block.super }}
{% if request.GET.sent %}
    {% editable page.form.response %}
    {{ page.form.response|richtext_filters|safe }}
    {% endeditable %}
{% else %}
    {% with page.form as page_form %}
    {% editable page_form.content %}
    {{ page_form.content|richtext_filters|safe }}
    {% endeditable %}
    {% endwith %}

    {% errors_for form %}

    <form class="mezzanine-form" method="post"{% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>
        {% fields_for form %}
        <div class="form-actions">
            <input class="btn btn-primary btn-lg" type="submit"
                value="{% if page.form.button_text %}{{ page.form.button_text }}{% else %}{% trans "Submit" %}{% endif %}">
        </div>
    </form>
{% endif %}

{% endblock %}


{% block extra_js %}
{{ block.super }}
<script>
$(function() {$('.mezzanine-form :input:visible:enabled:first').focus();});
</script>
{% endblock %}

templates/pages/blog_post_edit.html
{% extends "pages/page.html" %}

{% load mezzanine_tags i18n %}

{% block extra_head %}
    {{ block.super }}
    {{ form.media }}
{% endblock %}

{% block main %}
{{ block.super }}
{% if request.GET.sent %}
    {% editable page.form.response %}
    {{ page.form.response|richtext_filters|safe }}
    {% endeditable %}
{% else %}
    {% with page.form as page_form %}
    {% editable page_form.content %}
    {{ page_form.content|richtext_filters|safe }}
    {% endeditable %}
    {% endwith %}

    {% errors_for form %}

    <form class="mezzanine-form" method="post"{% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>
        {% fields_for form %}
        <div class="form-actions">
            <input class="btn btn-primary btn-lg" type="submit"
                value="{% if page.form.button_text %}{{ page.form.button_text }}{% else %}{% trans "Submit" %}{% endif %}">
        </div>
    </form>
{% endif %}

{% endblock %}


{% block extra_js %}
{{ block.super }}
<script>
$(function() {$('.mezzanine-form :input:visible:enabled:first').focus();});
</script>
{% endblock %}

templates/pages/form.html
{% extends "pages/page.html" %}

{% load mezzanine_tags i18n %}

{% block extra_head %}
    {{ block.super }}
    {{ form.media }}
{% endblock %}

{% block main %}
{{ block.super }}
{% if request.GET.sent %}
    {% editable page.form.response %}
    {{ page.form.response|richtext_filters|safe }}
    {% endeditable %}
{% else %}
    {% with page.form as page_form %}
    {% editable page_form.content %}
    {{ page_form.content|richtext_filters|safe }}
    {% endeditable %}
    {% endwith %}

    {% errors_for form %}

    <form class="mezzanine-form" method="post"{% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>
        {% fields_for form %}
        <div class="form-actions">
            <input class="btn btn-primary btn-lg" type="submit"
                value="{% if page.form.button_text %}{{ page.form.button_text }}{% else %}{% trans "Submit" %}{% endif %}">
        </div>
    </form>
{% endif %}

{% endblock %}


{% block extra_js %}
{{ block.super }}
<script>
$(function() {$('.mezzanine-form :input:visible:enabled:first').focus();});
</script>
{% endblock %}

templates/pages/gallery.html
{% extends "pages/page.html" %}

{% load mezzanine_tags staticfiles %}

{% block extra_css %}
<link rel="stylesheet" href="{% static "mezzanine/css/magnific-popup.css" %}">
{% endblock extra_css %}

{% block main %}
{{ block.super }}

{% editable page.gallery.content %}
{{ page.gallery.content|richtext_filters|safe }}
{% endeditable %}

<div class="gallery row">
{% with page.gallery.images.all as images %}
{% for image in images %}
<div class="col-xs-4 col-sm-3">
    <a class="thumbnail" rel="#image-{{ image.id }}" title="{{ image.description }}" href="{{ image.file.url }}">
        <img class="img-responsive" src="{{ MEDIA_URL }}{% thumbnail image.file 131 75 %}">
    </a>
</div>
{% endfor %}
{% endwith %}
</div>
{% endblock %}

{% block extra_js %}
{{ block.super }}
<script src="{% static "mezzanine/js/magnific-popup.js" %}"></script>
<script>
$(document).ready(function() {
    $('.gallery').magnificPopup({
        delegate: 'a',
        type: 'image',
        gallery: {
            enabled: true,
        }
    });
});
</script>
{% endblock %}

templates/pages/index.html
{% extends "pages/richtextpage.html" %}

{% block main %}
<!--
This template is provided as a custom template for the homepage, for
when it is configured as an editable page in the navigation tree. Feel
free to modify it.
-->
{{ block.super }}
{% endblock %}

templates/pages/page.html
{% extends "base.html" %}
{% load mezzanine_tags keyword_tags %}

{% block meta_title %}{{ page.meta_title }}{% endblock %}

{% block meta_keywords %}{% metablock %}
{% keywords_for page as keywords %}
{% for keyword in keywords %}
    {% if not forloop.first %}, {% endif %}
    {{ keyword }}
{% endfor %}
{% endmetablock %}{% endblock %}

{% block meta_description %}{% metablock %}
{{ page.description }}
{% endmetablock %}{% endblock %}

{% block title %}
{% editable page.title %}{{ page.title }}{% endeditable %}
{% endblock %}

{% block main %}
{% endblock %}

templates/pages/richtextpage.html
{% extends "pages/page.html" %}

{% load mezzanine_tags %}

{% block main %}{{ block.super }}

{% editable page.richtextpage.content %}
{{ page.richtextpage.content|richtext_filters|safe }}
{% endeditable %}

{% endblock %}